name: "Flake.lock: update Nix dependencies"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # runs monthly

jobs:
  nix-flake-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/update-flake-lock@v28
        with:
          token: ${{ secrets.FLAKE_LOCK_UPDATE_TOKEN }}
          pr-labels: |
            dependencies
